script "CoreServerGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCServerGetErrorMode
on TestGetErrorMode
   TestSkip "GetErrorMode", "not yet implemented"
end TestGetErrorMode

-- MCServerGetOutputTextEncoding
on TestGetOutputTextEncoding
   TestSkip "GetOutputTextEncoding", "not yet implemented"
end TestGetOutputTextEncoding

-- MCServerGetOutputLineEnding
on TestGetOutputLineEnding
   TestSkip "GetOutputLineEnding", "not yet implemented"
end TestGetOutputLineEnding

-- MCServerGetSessionSavePath
on TestGetSessionSavePath
   TestSkip "GetSessionSavePath", "not yet implemented"
end TestGetSessionSavePath

-- MCServerGetSessionLifetime
on TestGetSessionLifetime
   TestSkip "GetSessionLifetime", "not yet implemented"
end TestGetSessionLifetime

-- MCServerGetSessionCookieName
on TestGetSessionCookieName
   TestSkip "GetSessionCookieName", "not yet implemented"
end TestGetSessionCookieName

-- MCServerGetSessionId
on TestGetSessionId
   TestSkip "GetSessionId", "not yet implemented"
end TestGetSessionId

-- MCServerSetErrorMode
on TestSetErrorMode
   TestSkip "SetErrorMode", "not yet implemented"
end TestSetErrorMode

-- MCServerSetOutputTextEncoding
on TestSetOutputTextEncoding
   TestSkip "SetOutputTextEncoding", "not yet implemented"
end TestSetOutputTextEncoding

-- MCServerSetOutputLineEnding
on TestSetOutputLineEnding
   TestSkip "SetOutputLineEnding", "not yet implemented"
end TestSetOutputLineEnding

-- MCServerSetSessionSavePath
on TestSetSessionSavePath
   TestSkip "SetSessionSavePath", "not yet implemented"
end TestSetSessionSavePath

-- MCServerSetSessionLifetime
on TestSetSessionLifetime
   TestSkip "SetSessionLifetime", "not yet implemented"
end TestSetSessionLifetime

-- MCServerSetSessionCookieName
on TestSetSessionCookieName
   TestSkip "SetSessionCookieName", "not yet implemented"
end TestSetSessionCookieName

-- MCServerSetSessionId
on TestSetSessionId
   TestSkip "SetSessionId", "not yet implemented"
end TestSetSessionId
