script "CoreServerPut"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCServerExecPutHeader
on TestPutHeader
   TestSkip "PutHeader", "not yet implemented"
end TestPutHeader

-- MCServerExecPutBinaryOutput
on TestPutBinaryOutput
   TestSkip "PutBinaryOutput", "not yet implemented"
end TestPutBinaryOutput

-- MCServerExecPutContent
on TestPutContent
   TestSkip "PutContent", "not yet implemented"
end TestPutContent

-- MCServerExecPutMarkup
on TestPutMarkup
   TestSkip "PutMarkup", "not yet implemented"
end TestPutMarkup

-- MCServerExecPutCookie
on TestPutCookie
   TestSkip "PutCookie", "not yet implemented"
end TestPutCookie
