script "CorePrintingGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCPrintingGetPrinterNames
on TestGetPrinterNames
   TestSkip "GetPrinterNames", "not yet implemented"
end TestGetPrinterNames

-- MCPrintingGetPrintDeviceName
on TestGetPrintDeviceName
   TestSkip "GetPrintDeviceName", "not yet implemented"
end TestGetPrintDeviceName

-- MCPrintingGetPrintDeviceSettings
on TestGetPrintDeviceSettings
   TestSkip "GetPrintDeviceSettings", "not yet implemented"
end TestGetPrintDeviceSettings

-- MCPrintingGetPrintDeviceOutput
on TestGetPrintDeviceOutput
   TestSkip "GetPrintDeviceOutput", "not yet implemented"
end TestGetPrintDeviceOutput

-- MCPrintingGetPrintDeviceFeatures
on TestGetPrintDeviceFeatures
   TestSkip "GetPrintDeviceFeatures", "not yet implemented"
end TestGetPrintDeviceFeatures

-- MCPrintingGetPrintDeviceRectangle
on TestGetPrintDeviceRectangle
   TestSkip "GetPrintDeviceRectangle", "not yet implemented"
end TestGetPrintDeviceRectangle

-- MCPrintingGetPrintPageSize
on TestGetPrintPageSize
   TestSkip "GetPrintPageSize", "not yet implemented"
end TestGetPrintPageSize

-- MCPrintingGetPrintPageRectangle
on TestGetPrintPageRectangle
   TestSkip "GetPrintPageRectangle", "not yet implemented"
end TestGetPrintPageRectangle

-- MCPrintingGetPrintPageOrientation
on TestGetPrintPageOrientation
   TestSkip "GetPrintPageOrientation", "not yet implemented"
end TestGetPrintPageOrientation

-- MCPrintingGetPrintPageScale
on TestGetPrintPageScale
   TestSkip "GetPrintPageScale", "not yet implemented"
end TestGetPrintPageScale

-- MCPrintingGetPrintJobName
on TestGetPrintJobName
   TestSkip "GetPrintJobName", "not yet implemented"
end TestGetPrintJobName

-- MCPrintingGetPrintJobCopies
on TestGetPrintJobCopies
   TestSkip "GetPrintJobCopies", "not yet implemented"
end TestGetPrintJobCopies

-- MCPrintingGetPrintJobDuplex
on TestGetPrintJobDuplex
   TestSkip "GetPrintJobDuplex", "not yet implemented"
end TestGetPrintJobDuplex

-- MCPrintingGetPrintJobCollate
on TestGetPrintJobCollate
   TestSkip "GetPrintJobCollate", "not yet implemented"
end TestGetPrintJobCollate

-- MCPrintingGetPrintJobColor
on TestGetPrintJobColor
   TestSkip "GetPrintJobColor", "not yet implemented"
end TestGetPrintJobColor

-- MCPrintingGetPrintJobRanges
on TestGetPrintJobRanges
   TestSkip "GetPrintJobRanges", "not yet implemented"
end TestGetPrintJobRanges

-- MCPrintingGetPrintJobPage
on TestGetPrintJobPage
   TestSkip "GetPrintJobPage", "not yet implemented"
end TestGetPrintJobPage

-- MCPrintingGetPrintCardBorders
on TestGetPrintCardBorders
   TestSkip "GetPrintCardBorders", "not yet implemented"
end TestGetPrintCardBorders

-- MCPrintingGetPrintGutters
on TestGetPrintGutters
   TestSkip "GetPrintGutters", "not yet implemented"
end TestGetPrintGutters

-- MCPrintingGetPrintMargins
on TestGetPrintMargins
   TestSkip "GetPrintMargins", "not yet implemented"
end TestGetPrintMargins

-- MCPrintingGetPrintRowsFirst
on TestGetPrintRowsFirst
   TestSkip "GetPrintRowsFirst", "not yet implemented"
end TestGetPrintRowsFirst

-- MCPrintingGetPrintScale
on TestGetPrintScale
   TestSkip "GetPrintScale", "not yet implemented"
end TestGetPrintScale

-- MCPrintingGetPrintRotated
on TestGetPrintRotated
   TestSkip "GetPrintRotated", "not yet implemented"
end TestGetPrintRotated

-- MCPrintingGetPrintCommand
on TestGetPrintCommand
   TestSkip "GetPrintCommand", "not yet implemented"
end TestGetPrintCommand

-- MCPrintingGetPrintFontTable
on TestGetPrintFontTable
   TestSkip "GetPrintFontTable", "not yet implemented"
end TestGetPrintFontTable

-- MCPrintingSetPrintDeviceName
on TestSetPrintDeviceName
   TestSkip "SetPrintDeviceName", "not yet implemented"
end TestSetPrintDeviceName

-- MCPrintingSetPrintDeviceOutput
on TestSetPrintDeviceOutput
   TestSkip "SetPrintDeviceOutput", "not yet implemented"
end TestSetPrintDeviceOutput

-- MCPrintingSetPrintPageSize
on TestSetPrintPageSize
   TestSkip "SetPrintPageSize", "not yet implemented"
end TestSetPrintPageSize

-- MCPrintingSetPrintPageOrientation
on TestSetPrintPageOrientation
   TestSkip "SetPrintPageOrientation", "not yet implemented"
end TestSetPrintPageOrientation

-- MCPrintingSetPrintPageScale
on TestSetPrintPageScale
   TestSkip "SetPrintPageScale", "not yet implemented"
end TestSetPrintPageScale

-- MCPrintingSetPrintJobName
on TestSetPrintJobName
   TestSkip "SetPrintJobName", "not yet implemented"
end TestSetPrintJobName

-- MCPrintingSetPrintJobCopies
on TestSetPrintJobCopies
   TestSkip "SetPrintJobCopies", "not yet implemented"
end TestSetPrintJobCopies

-- MCPrintingSetPrintJobDuplex
on TestSetPrintJobDuplex
   TestSkip "SetPrintJobDuplex", "not yet implemented"
end TestSetPrintJobDuplex

-- MCPrintingSetPrintJobCollate
on TestSetPrintJobCollate
   TestSkip "SetPrintJobCollate", "not yet implemented"
end TestSetPrintJobCollate

-- MCPrintingSetPrintJobColor
on TestSetPrintJobColor
   TestSkip "SetPrintJobColor", "not yet implemented"
end TestSetPrintJobColor

-- MCPrintingSetPrintJobRanges
on TestSetPrintJobRanges
   TestSkip "SetPrintJobRanges", "not yet implemented"
end TestSetPrintJobRanges

-- MCPrintingSetPrintCardBorders
on TestSetPrintCardBorders
   TestSkip "SetPrintCardBorders", "not yet implemented"
end TestSetPrintCardBorders

-- MCPrintingSetPrintGutters
on TestSetPrintGutters
   TestSkip "SetPrintGutters", "not yet implemented"
end TestSetPrintGutters

-- MCPrintingSetPrintMargins
on TestSetPrintMargins
   TestSkip "SetPrintMargins", "not yet implemented"
end TestSetPrintMargins

-- MCPrintingSetPrintRowsFirst
on TestSetPrintRowsFirst
   TestSkip "SetPrintRowsFirst", "not yet implemented"
end TestSetPrintRowsFirst

-- MCPrintingSetPrintScale
on TestSetPrintScale
   TestSkip "SetPrintScale", "not yet implemented"
end TestSetPrintScale

-- MCPrintingSetPrintRotated
on TestSetPrintRotated
   TestSkip "SetPrintRotated", "not yet implemented"
end TestSetPrintRotated

-- MCPrintingSetPrintCommand
on TestSetPrintCommand
   TestSkip "SetPrintCommand", "not yet implemented"
end TestSetPrintCommand

-- MCPrintingSetPrintFontTable
on TestSetPrintFontTable
   TestSkip "SetPrintFontTable", "not yet implemented"
end TestSetPrintFontTable
