script "CorePrintingPrint"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCPrintingExecPrintAnchor
on TestPrintAnchor
   TestSkip "PrintAnchor", "not yet implemented"
end TestPrintAnchor

-- MCPrintingExecPrintLink
on TestPrintLink
   TestSkip "PrintLink", "not yet implemented"
end TestPrintLink

-- MCPrintingExecPrintUnicodeBookmark
on TestPrintUnicodeBookmark
   TestSkip "PrintUnicodeBookmark", "not yet implemented"
end TestPrintUnicodeBookmark

-- MCPrintingExecPrintBreak
on TestPrintBreak
   TestSkip "PrintBreak", "not yet implemented"
end TestPrintBreak

-- MCPrintingExecPrintAllCards
on TestPrintAllCards
   TestSkip "PrintAllCards", "not yet implemented"
end TestPrintAllCards

-- MCPrintingExecPrintRectOfAllCards
on TestPrintRectOfAllCards
   TestSkip "PrintRectOfAllCards", "not yet implemented"
end TestPrintRectOfAllCards

-- MCPrintingExecPrintCard
on TestPrintCard
   TestSkip "PrintCard", "not yet implemented"
end TestPrintCard

-- MCPrintingExecPrintRectOfCard
on TestPrintRectOfCard
   TestSkip "PrintRectOfCard", "not yet implemented"
end TestPrintRectOfCard

-- MCPrintingExecPrintSomeCards
on TestPrintSomeCards
   TestSkip "PrintSomeCards", "not yet implemented"
end TestPrintSomeCards

-- MCPrintingExecPrintRectOfSomeCards
on TestPrintRectOfSomeCards
   TestSkip "PrintRectOfSomeCards", "not yet implemented"
end TestPrintRectOfSomeCards

-- MCPrintingExecPrintCardIntoRect
on TestPrintCardIntoRect
   TestSkip "PrintCardIntoRect", "not yet implemented"
end TestPrintCardIntoRect

-- MCPrintingExecPrintRectOfCardIntoRect
on TestPrintRectOfCardIntoRect
   TestSkip "PrintRectOfCardIntoRect", "not yet implemented"
end TestPrintRectOfCardIntoRect
