script "CoreDebuggingGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCDebuggingGetBreakpoints
on TestGetBreakpoints
   TestSkip "GetBreakpoints", "not yet implemented"
end TestGetBreakpoints

-- MCDebuggingGetDebugContext
on TestGetDebugContext
   TestSkip "GetDebugContext", "not yet implemented"
end TestGetDebugContext

-- MCDebuggingGetMessageMessages
on TestGetMessageMessages
   TestSkip "GetMessageMessages", "not yet implemented"
end TestGetMessageMessages

-- MCDebuggingGetWatchedVariables
on TestGetWatchedVariables
   TestSkip "GetWatchedVariables", "not yet implemented"
end TestGetWatchedVariables

-- MCDebuggingGetTraceAbort
on TestGetTraceAbort
   TestSkip "GetTraceAbort", "not yet implemented"
end TestGetTraceAbort

-- MCDebuggingGetTraceDelay
on TestGetTraceDelay
   TestSkip "GetTraceDelay", "not yet implemented"
end TestGetTraceDelay

-- MCDebuggingGetTraceReturn
on TestGetTraceReturn
   TestSkip "GetTraceReturn", "not yet implemented"
end TestGetTraceReturn

-- MCDebuggingGetTraceStack
on TestGetTraceStack
   TestSkip "GetTraceStack", "not yet implemented"
end TestGetTraceStack

-- MCDebuggingGetTraceUntil
on TestGetTraceUntil
   TestSkip "GetTraceUntil", "not yet implemented"
end TestGetTraceUntil

-- MCDebuggingSetBreakpoints
on TestSetBreakpoints
   TestSkip "SetBreakpoints", "not yet implemented"
end TestSetBreakpoints

-- MCDebuggingSetDebugContext
on TestSetDebugContext
   TestSkip "SetDebugContext", "not yet implemented"
end TestSetDebugContext

-- MCDebuggingSetMessageMessages
on TestSetMessageMessages
   TestSkip "SetMessageMessages", "not yet implemented"
end TestSetMessageMessages

-- MCDebuggingSetWatchedVariables
on TestSetWatchedVariables
   TestSkip "SetWatchedVariables", "not yet implemented"
end TestSetWatchedVariables

-- MCDebuggingSetTraceAbort
on TestSetTraceAbort
   TestSkip "SetTraceAbort", "not yet implemented"
end TestSetTraceAbort

-- MCDebuggingSetTraceDelay
on TestSetTraceDelay
   TestSkip "SetTraceDelay", "not yet implemented"
end TestSetTraceDelay

-- MCDebuggingSetTraceReturn
on TestSetTraceReturn
   TestSkip "SetTraceReturn", "not yet implemented"
end TestSetTraceReturn

-- MCDebuggingSetTraceStack
on TestSetTraceStack
   TestSkip "SetTraceStack", "not yet implemented"
end TestSetTraceStack

-- MCDebuggingSetTraceUntil
on TestSetTraceUntil
   TestSkip "SetTraceUntil", "not yet implemented"
end TestSetTraceUntil
