script "CoreFilesGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCFilesEvalGetResource
on TestGetResource
   TestSkip "GetResource", "not yet implemented"
end TestGetResource

-- MCFilesEvalGetResources
on TestGetResources
   TestSkip "GetResources", "not yet implemented"
end TestGetResources

-- MCFilesEvalGetResources
on TestGetResources
   TestSkip "GetResources", "not yet implemented"
end TestGetResources

-- MCFilesEvalSetResource
on TestSetResource
   TestSkip "SetResource", "not yet implemented"
end TestSetResource

-- MCFilesGetUMask
on TestGetUMask
   TestSkip "GetUMask", "not yet implemented"
end TestGetUMask

-- MCFilesGetFileType
on TestGetFileType
   TestSkip "GetFileType", "not yet implemented"
end TestGetFileType

-- MCFilesGetSerialControlString
on TestGetSerialControlString
   TestSkip "GetSerialControlString", "not yet implemented"
end TestGetSerialControlString

-- MCFilesGetHideConsoleWindows
on TestGetHideConsoleWindows
   TestSkip "GetHideConsoleWindows", "not yet implemented"
end TestGetHideConsoleWindows

-- MCFilesGetShellCommand
on TestGetShellCommand
   TestSkip "GetShellCommand", "not yet implemented"
end TestGetShellCommand

-- MCFilesGetCurrentFolder
on TestGetCurrentFolder
   TestSkip "GetCurrentFolder", "not yet implemented"
end TestGetCurrentFolder

-- MCFilesGetEngineFolder
on TestGetEngineFolder
   TestSkip "GetEngineFolder", "not yet implemented"
end TestGetEngineFolder

-- MCFilesGetHomeFolder
on TestGetHomeFolder
   TestSkip "GetHomeFolder", "not yet implemented"
end TestGetHomeFolder

-- MCFilesGetDocumentsFolder
on TestGetDocumentsFolder
   TestSkip "GetDocumentsFolder", "not yet implemented"
end TestGetDocumentsFolder

-- MCFilesGetDesktopFolder
on TestGetDesktopFolder
   TestSkip "GetDesktopFolder", "not yet implemented"
end TestGetDesktopFolder

-- MCFilesGetTemporaryFolder
on TestGetTemporaryFolder
   TestSkip "GetTemporaryFolder", "not yet implemented"
end TestGetTemporaryFolder

-- MCFilesGetFiles
on TestGetFiles
   TestSkip "GetFiles", "not yet implemented"
end TestGetFiles

-- MCFilesGetDetailedFiles
on TestGetDetailedFiles
   TestSkip "GetDetailedFiles", "not yet implemented"
end TestGetDetailedFiles

-- MCFilesGetFolders
on TestGetFolders
   TestSkip "GetFolders", "not yet implemented"
end TestGetFolders

-- MCFilesGetDetailedFolders
on TestGetDetailedFolders
   TestSkip "GetDetailedFolders", "not yet implemented"
end TestGetDetailedFolders

-- MCFilesSetUMask
on TestSetUMask
   TestSkip "SetUMask", "not yet implemented"
end TestSetUMask

-- MCFilesSetFileType
on TestSetFileType
   TestSkip "SetFileType", "not yet implemented"
end TestSetFileType

-- MCFilesSetSerialControlString
on TestSetSerialControlString
   TestSkip "SetSerialControlString", "not yet implemented"
end TestSetSerialControlString

-- MCFilesSetHideConsoleWindows
on TestSetHideConsoleWindows
   TestSkip "SetHideConsoleWindows", "not yet implemented"
end TestSetHideConsoleWindows

-- MCFilesSetShellCommand
on TestSetShellCommand
   TestSkip "SetShellCommand", "not yet implemented"
end TestSetShellCommand

-- MCFilesSetCurrentFolder
on TestSetCurrentFolder
   TestSkip "SetCurrentFolder", "not yet implemented"
end TestSetCurrentFolder
