script "CoreFilesRead"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCFilesExecReadFromStdinFor
on TestReadFromStdinFor
   TestSkip "ReadFromStdinFor", "not yet implemented"
end TestReadFromStdinFor

-- MCFilesExecReadFromStdinUntil
on TestReadFromStdinUntil
   TestSkip "ReadFromStdinUntil", "not yet implemented"
end TestReadFromStdinUntil

-- MCFilesExecReadFromFileOrDriverFor
on TestReadFromFileOrDriverFor
   TestSkip "ReadFromFileOrDriverFor", "not yet implemented"
end TestReadFromFileOrDriverFor

-- MCFilesExecReadFromFileOrDriverUntil
on TestReadFromFileOrDriverUntil
   TestSkip "ReadFromFileOrDriverUntil", "not yet implemented"
end TestReadFromFileOrDriverUntil

-- MCFilesExecReadFromFileOrDriverAtFor
on TestReadFromFileOrDriverAtFor
   TestSkip "ReadFromFileOrDriverAtFor", "not yet implemented"
end TestReadFromFileOrDriverAtFor

-- MCFilesExecReadFromFileOrDriverAtUntil
on TestReadFromFileOrDriverAtUntil
   TestSkip "ReadFromFileOrDriverAtUntil", "not yet implemented"
end TestReadFromFileOrDriverAtUntil

-- MCFilesExecReadFromFileOrDriverAtEndFor
on TestReadFromFileOrDriverAtEndFor
   TestSkip "ReadFromFileOrDriverAtEndFor", "not yet implemented"
end TestReadFromFileOrDriverAtEndFor

-- MCFilesExecReadFromFileOrDriverAtEndUntil
on TestReadFromFileOrDriverAtEndUntil
   TestSkip "ReadFromFileOrDriverAtEndUntil", "not yet implemented"
end TestReadFromFileOrDriverAtEndUntil

-- MCFilesExecReadFromProcessFor
on TestReadFromProcessFor
   TestSkip "ReadFromProcessFor", "not yet implemented"
end TestReadFromProcessFor

-- MCFilesExecReadFromProcessUntil
on TestReadFromProcessUntil
   TestSkip "ReadFromProcessUntil", "not yet implemented"
end TestReadFromProcessUntil
