script "CoreFilesWrite"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCFilesExecWriteToStdout
on TestWriteToStdout
   TestSkip "WriteToStdout", "not yet implemented"
end TestWriteToStdout

-- MCFilesExecWriteToStderr
on TestWriteToStderr
   TestSkip "WriteToStderr", "not yet implemented"
end TestWriteToStderr

-- MCFilesExecWriteToFileOrDriver
on TestWriteToFileOrDriver
   TestSkip "WriteToFileOrDriver", "not yet implemented"
end TestWriteToFileOrDriver

-- MCFilesExecWriteToFileOrDriverAt
on TestWriteToFileOrDriverAt
   TestSkip "WriteToFileOrDriverAt", "not yet implemented"
end TestWriteToFileOrDriverAt

-- MCFilesExecWriteToFileOrDriverAtEnd
on TestWriteToFileOrDriverAtEnd
   TestSkip "WriteToFileOrDriverAtEnd", "not yet implemented"
end TestWriteToFileOrDriverAtEnd

-- MCFilesExecWriteToProcess
on TestWriteToProcess
   TestSkip "WriteToProcess", "not yet implemented"
end TestWriteToProcess
