script "CoreDialogAsk"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCDialogExecAskQuestion
on TestAskQuestion
   TestSkip "AskQuestion", "not yet implemented"
end TestAskQuestion

-- MCDialogExecAskPassword
on TestAskPassword
   TestSkip "AskPassword", "not yet implemented"
end TestAskPassword

-- MCDialogExecAskFile
on TestAskFile
   TestSkip "AskFile", "not yet implemented"
end TestAskFile

-- MCDialogExecAskFileWithFilter
on TestAskFileWithFilter
   TestSkip "AskFileWithFilter", "not yet implemented"
end TestAskFileWithFilter

-- MCDialogExecAskFileWithTypes
on TestAskFileWithTypes
   TestSkip "AskFileWithTypes", "not yet implemented"
end TestAskFileWithTypes
