script "CoreLegacyGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCLegacyGetRevRuntimeBehaviour
on TestGetRevRuntimeBehaviour
   TestSkip "GetRevRuntimeBehaviour", "not yet implemented"
end TestGetRevRuntimeBehaviour

-- MCLegacyGetHcImportStat
on TestGetHcImportStat
   TestSkip "GetHcImportStat", "not yet implemented"
end TestGetHcImportStat

-- MCLegacyGetScriptTextFont
on TestGetScriptTextFont
   TestSkip "GetScriptTextFont", "not yet implemented"
end TestGetScriptTextFont

-- MCLegacyGetScriptTextSize
on TestGetScriptTextSize
   TestSkip "GetScriptTextSize", "not yet implemented"
end TestGetScriptTextSize

-- MCLegacyGetBufferMode
on TestGetBufferMode
   TestSkip "GetBufferMode", "not yet implemented"
end TestGetBufferMode

-- MCLegacyGetMultiEffect
on TestGetMultiEffect
   TestSkip "GetMultiEffect", "not yet implemented"
end TestGetMultiEffect

-- MCLegacyGetEditScripts
on TestGetEditScripts
   TestSkip "GetEditScripts", "not yet implemented"
end TestGetEditScripts

-- MCLegacyGetColorWorld
on TestGetColorWorld
   TestSkip "GetColorWorld", "not yet implemented"
end TestGetColorWorld

-- MCLegacyGetAllowKeyInField
on TestGetAllowKeyInField
   TestSkip "GetAllowKeyInField", "not yet implemented"
end TestGetAllowKeyInField

-- MCLegacyGetAllowFieldRedraw
on TestGetAllowFieldRedraw
   TestSkip "GetAllowFieldRedraw", "not yet implemented"
end TestGetAllowFieldRedraw

-- MCLegacyGetRemapColor
on TestGetRemapColor
   TestSkip "GetRemapColor", "not yet implemented"
end TestGetRemapColor

-- MCLegacyGetUserLevel
on TestGetUserLevel
   TestSkip "GetUserLevel", "not yet implemented"
end TestGetUserLevel

-- MCLegacyGetUserModify
on TestGetUserModify
   TestSkip "GetUserModify", "not yet implemented"
end TestGetUserModify

-- MCLegacyGetLockColormap
on TestGetLockColormap
   TestSkip "GetLockColormap", "not yet implemented"
end TestGetLockColormap

-- MCLegacyGetPrivateColors
on TestGetPrivateColors
   TestSkip "GetPrivateColors", "not yet implemented"
end TestGetPrivateColors

-- MCLegacyGetLongWindowTitles
on TestGetLongWindowTitles
   TestSkip "GetLongWindowTitles", "not yet implemented"
end TestGetLongWindowTitles

-- MCLegacyGetBlindTyping
on TestGetBlindTyping
   TestSkip "GetBlindTyping", "not yet implemented"
end TestGetBlindTyping

-- MCLegacyGetPowerKeys
on TestGetPowerKeys
   TestSkip "GetPowerKeys", "not yet implemented"
end TestGetPowerKeys

-- MCLegacyGetTextArrows
on TestGetTextArrows
   TestSkip "GetTextArrows", "not yet implemented"
end TestGetTextArrows

-- MCLegacyGetColormap
on TestGetColormap
   TestSkip "GetColormap", "not yet implemented"
end TestGetColormap

-- MCLegacyGetNoPixmaps
on TestGetNoPixmaps
   TestSkip "GetNoPixmaps", "not yet implemented"
end TestGetNoPixmaps

-- MCLegacyGetLowResolutionTimers
on TestGetLowResolutionTimers
   TestSkip "GetLowResolutionTimers", "not yet implemented"
end TestGetLowResolutionTimers

-- MCLegacyGetVcSharedMemory
on TestGetVcSharedMemory
   TestSkip "GetVcSharedMemory", "not yet implemented"
end TestGetVcSharedMemory

-- MCLegacyGetVcPlayer
on TestGetVcPlayer
   TestSkip "GetVcPlayer", "not yet implemented"
end TestGetVcPlayer

-- MCLegacyGetSoundChannel
on TestGetSoundChannel
   TestSkip "GetSoundChannel", "not yet implemented"
end TestGetSoundChannel

-- MCLegacyGetLzwKey
on TestGetLzwKey
   TestSkip "GetLzwKey", "not yet implemented"
end TestGetLzwKey

-- MCLegacyGetMultiple
on TestGetMultiple
   TestSkip "GetMultiple", "not yet implemented"
end TestGetMultiple

-- MCLegacyGetMultiSpace
on TestGetMultiSpace
   TestSkip "GetMultiSpace", "not yet implemented"
end TestGetMultiSpace

-- MCLegacyGetMenuBar
on TestGetMenuBar
   TestSkip "GetMenuBar", "not yet implemented"
end TestGetMenuBar

-- MCLegacySetRevRuntimeBehaviour
on TestSetRevRuntimeBehaviour
   TestSkip "SetRevRuntimeBehaviour", "not yet implemented"
end TestSetRevRuntimeBehaviour

-- MCLegacySetHcImportStat
on TestSetHcImportStat
   TestSkip "SetHcImportStat", "not yet implemented"
end TestSetHcImportStat

-- MCLegacySetScriptTextFont
on TestSetScriptTextFont
   TestSkip "SetScriptTextFont", "not yet implemented"
end TestSetScriptTextFont

-- MCLegacySetScriptTextSize
on TestSetScriptTextSize
   TestSkip "SetScriptTextSize", "not yet implemented"
end TestSetScriptTextSize

-- MCLegacySetBufferMode
on TestSetBufferMode
   TestSkip "SetBufferMode", "not yet implemented"
end TestSetBufferMode

-- MCLegacySetMultiEffect
on TestSetMultiEffect
   TestSkip "SetMultiEffect", "not yet implemented"
end TestSetMultiEffect

-- MCLegacySetEditScripts
on TestSetEditScripts
   TestSkip "SetEditScripts", "not yet implemented"
end TestSetEditScripts

-- MCLegacySetColorWorld
on TestSetColorWorld
   TestSkip "SetColorWorld", "not yet implemented"
end TestSetColorWorld

-- MCLegacySetAllowKeyInField
on TestSetAllowKeyInField
   TestSkip "SetAllowKeyInField", "not yet implemented"
end TestSetAllowKeyInField

-- MCLegacySetAllowFieldRedraw
on TestSetAllowFieldRedraw
   TestSkip "SetAllowFieldRedraw", "not yet implemented"
end TestSetAllowFieldRedraw

-- MCLegacySetRemapColor
on TestSetRemapColor
   TestSkip "SetRemapColor", "not yet implemented"
end TestSetRemapColor

-- MCLegacySetUserLevel
on TestSetUserLevel
   TestSkip "SetUserLevel", "not yet implemented"
end TestSetUserLevel

-- MCLegacySetUserModify
on TestSetUserModify
   TestSkip "SetUserModify", "not yet implemented"
end TestSetUserModify

-- MCLegacySetLockColormap
on TestSetLockColormap
   TestSkip "SetLockColormap", "not yet implemented"
end TestSetLockColormap

-- MCLegacySetPrivateColors
on TestSetPrivateColors
   TestSkip "SetPrivateColors", "not yet implemented"
end TestSetPrivateColors

-- MCLegacySetLongWindowTitles
on TestSetLongWindowTitles
   TestSkip "SetLongWindowTitles", "not yet implemented"
end TestSetLongWindowTitles

-- MCLegacySetBlindTyping
on TestSetBlindTyping
   TestSkip "SetBlindTyping", "not yet implemented"
end TestSetBlindTyping

-- MCLegacySetPowerKeys
on TestSetPowerKeys
   TestSkip "SetPowerKeys", "not yet implemented"
end TestSetPowerKeys

-- MCLegacySetTextArrows
on TestSetTextArrows
   TestSkip "SetTextArrows", "not yet implemented"
end TestSetTextArrows

-- MCLegacySetColormap
on TestSetColormap
   TestSkip "SetColormap", "not yet implemented"
end TestSetColormap

-- MCLegacySetNoPixmaps
on TestSetNoPixmaps
   TestSkip "SetNoPixmaps", "not yet implemented"
end TestSetNoPixmaps

-- MCLegacySetLowResolutionTimers
on TestSetLowResolutionTimers
   TestSkip "SetLowResolutionTimers", "not yet implemented"
end TestSetLowResolutionTimers

-- MCLegacySetVcSharedMemory
on TestSetVcSharedMemory
   TestSkip "SetVcSharedMemory", "not yet implemented"
end TestSetVcSharedMemory

-- MCLegacySetVcPlayer
on TestSetVcPlayer
   TestSkip "SetVcPlayer", "not yet implemented"
end TestSetVcPlayer

-- MCLegacySetSoundChannel
on TestSetSoundChannel
   TestSkip "SetSoundChannel", "not yet implemented"
end TestSetSoundChannel

-- MCLegacySetLzwKey
on TestSetLzwKey
   TestSkip "SetLzwKey", "not yet implemented"
end TestSetLzwKey

-- MCLegacySetMultiple
on TestSetMultiple
   TestSkip "SetMultiple", "not yet implemented"
end TestSetMultiple

-- MCLegacySetMultiSpace
on TestSetMultiSpace
   TestSkip "SetMultiSpace", "not yet implemented"
end TestSetMultiSpace
