script "CoreNetworkGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCNetworkGetUrlResponse
on TestGetUrlResponse
   TestSkip "GetUrlResponse", "not yet implemented"
end TestGetUrlResponse

-- MCNetworkGetFtpProxy
on TestGetFtpProxy
   TestSkip "GetFtpProxy", "not yet implemented"
end TestGetFtpProxy

-- MCNetworkGetHttpProxy
on TestGetHttpProxy
   TestSkip "GetHttpProxy", "not yet implemented"
end TestGetHttpProxy

-- MCNetworkGetHttpHeaders
on TestGetHttpHeaders
   TestSkip "GetHttpHeaders", "not yet implemented"
end TestGetHttpHeaders

-- MCNetworkGetSocketTimeout
on TestGetSocketTimeout
   TestSkip "GetSocketTimeout", "not yet implemented"
end TestGetSocketTimeout

-- MCNetworkGetDefaultNetworkInterface
on TestGetDefaultNetworkInterface
   TestSkip "GetDefaultNetworkInterface", "not yet implemented"
end TestGetDefaultNetworkInterface

-- MCNetworkGetNetworkInterfaces
on TestGetNetworkInterfaces
   TestSkip "GetNetworkInterfaces", "not yet implemented"
end TestGetNetworkInterfaces

-- MCNetworkSetFtpProxy
on TestSetFtpProxy
   TestSkip "SetFtpProxy", "not yet implemented"
end TestSetFtpProxy

-- MCNetworkSetHttpProxy
on TestSetHttpProxy
   TestSkip "SetHttpProxy", "not yet implemented"
end TestSetHttpProxy

-- MCNetworkSetHttpHeaders
on TestSetHttpHeaders
   TestSkip "SetHttpHeaders", "not yet implemented"
end TestSetHttpHeaders

-- MCNetworkSetSocketTimeout
on TestSetSocketTimeout
   TestSkip "SetSocketTimeout", "not yet implemented"
end TestSetSocketTimeout

-- MCNetworkSetDefaultNetworkInterface
on TestSetDefaultNetworkInterface
   TestSkip "SetDefaultNetworkInterface", "not yet implemented"
end TestSetDefaultNetworkInterface
