script "CoreMultimediaGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCMultimediaGetRecordFormat
on TestGetRecordFormat
   TestSkip "GetRecordFormat", "not yet implemented"
end TestGetRecordFormat

-- MCMultimediaGetRecordCompression
on TestGetRecordCompression
   TestSkip "GetRecordCompression", "not yet implemented"
end TestGetRecordCompression

-- MCMultimediaGetRecordInput
on TestGetRecordInput
   TestSkip "GetRecordInput", "not yet implemented"
end TestGetRecordInput

-- MCMultimediaGetRecordSampleSize
on TestGetRecordSampleSize
   TestSkip "GetRecordSampleSize", "not yet implemented"
end TestGetRecordSampleSize

-- MCMultimediaGetRecordChannels
on TestGetRecordChannels
   TestSkip "GetRecordChannels", "not yet implemented"
end TestGetRecordChannels

-- MCMultimediaGetRecordRate
on TestGetRecordRate
   TestSkip "GetRecordRate", "not yet implemented"
end TestGetRecordRate

-- MCMultimediaGetQtIdleRate
on TestGetQtIdleRate
   TestSkip "GetQtIdleRate", "not yet implemented"
end TestGetQtIdleRate

-- MCMultimediaGetDontUseQt
on TestGetDontUseQt
   TestSkip "GetDontUseQt", "not yet implemented"
end TestGetDontUseQt

-- MCMultimediaGetDontUseQtEffects
on TestGetDontUseQtEffects
   TestSkip "GetDontUseQtEffects", "not yet implemented"
end TestGetDontUseQtEffects

-- MCMultimediaGetRecording
on TestGetRecording
   TestSkip "GetRecording", "not yet implemented"
end TestGetRecording

-- MCMultimediaGetPlayDestination
on TestGetPlayDestination
   TestSkip "GetPlayDestination", "not yet implemented"
end TestGetPlayDestination

-- MCMultimediaGetPlayLoudness
on TestGetPlayLoudness
   TestSkip "GetPlayLoudness", "not yet implemented"
end TestGetPlayLoudness

-- MCMultimediaSetRecordFormat
on TestSetRecordFormat
   TestSkip "SetRecordFormat", "not yet implemented"
end TestSetRecordFormat

-- MCMultimediaSetRecordCompression
on TestSetRecordCompression
   TestSkip "SetRecordCompression", "not yet implemented"
end TestSetRecordCompression

-- MCMultimediaSetRecordInput
on TestSetRecordInput
   TestSkip "SetRecordInput", "not yet implemented"
end TestSetRecordInput

-- MCMultimediaSetRecordSampleSize
on TestSetRecordSampleSize
   TestSkip "SetRecordSampleSize", "not yet implemented"
end TestSetRecordSampleSize

-- MCMultimediaSetRecordChannels
on TestSetRecordChannels
   TestSkip "SetRecordChannels", "not yet implemented"
end TestSetRecordChannels

-- MCMultimediaSetRecordRate
on TestSetRecordRate
   TestSkip "SetRecordRate", "not yet implemented"
end TestSetRecordRate

-- MCMultimediaSetQtIdleRate
on TestSetQtIdleRate
   TestSkip "SetQtIdleRate", "not yet implemented"
end TestSetQtIdleRate

-- MCMultimediaSetDontUseQt
on TestSetDontUseQt
   TestSkip "SetDontUseQt", "not yet implemented"
end TestSetDontUseQt

-- MCMultimediaSetDontUseQtEffects
on TestSetDontUseQtEffects
   TestSkip "SetDontUseQtEffects", "not yet implemented"
end TestSetDontUseQtEffects

-- MCMultimediaSetRecording
on TestSetRecording
   TestSkip "SetRecording", "not yet implemented"
end TestSetRecording

-- MCMultimediaSetPlayDestination
on TestSetPlayDestination
   TestSkip "SetPlayDestination", "not yet implemented"
end TestSetPlayDestination

-- MCMultimediaSetPlayLoudness
on TestSetPlayLoudness
   TestSkip "SetPlayLoudness", "not yet implemented"
end TestSetPlayLoudness
