script "CoreMultimediaPlay"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCMultimediaExecPlayAudioClip
on TestPlayAudioClip
   TestSkip "PlayAudioClip", "not yet implemented"
end TestPlayAudioClip

-- MCMultimediaExecPlayVideoClip
on TestPlayVideoClip
   TestSkip "PlayVideoClip", "not yet implemented"
end TestPlayVideoClip

-- MCMultimediaExecPlayStopAudio
on TestPlayStopAudio
   TestSkip "PlayStopAudio", "not yet implemented"
end TestPlayStopAudio

-- MCMultimediaExecPlayPlayerOperation
on TestPlayPlayerOperation
   TestSkip "PlayPlayerOperation", "not yet implemented"
end TestPlayPlayerOperation

-- MCMultimediaExecPlayVideoOperation
on TestPlayVideoOperation
   TestSkip "PlayVideoOperation", "not yet implemented"
end TestPlayVideoOperation

-- MCMultimediaExecPlayLastVideoOperation
on TestPlayLastVideoOperation
   TestSkip "PlayLastVideoOperation", "not yet implemented"
end TestPlayLastVideoOperation
