script "CorePasteboardGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCPasteboardGetClipboardData
on TestGetClipboardData
   TestSkip "GetClipboardData", "not yet implemented"
end TestGetClipboardData

-- MCPasteboardGetDragData
on TestGetDragData
   TestSkip "GetDragData", "not yet implemented"
end TestGetDragData

-- MCPasteboardGetAcceptDrop
on TestGetAcceptDrop
   TestSkip "GetAcceptDrop", "not yet implemented"
end TestGetAcceptDrop

-- MCPasteboardGetDragAction
on TestGetDragAction
   TestSkip "GetDragAction", "not yet implemented"
end TestGetDragAction

-- MCPasteboardGetAllowableDragActions
on TestGetAllowableDragActions
   TestSkip "GetAllowableDragActions", "not yet implemented"
end TestGetAllowableDragActions

-- MCPasteboardGetDragImage
on TestGetDragImage
   TestSkip "GetDragImage", "not yet implemented"
end TestGetDragImage

-- MCPasteboardGetDragImageOffset
on TestGetDragImageOffset
   TestSkip "GetDragImageOffset", "not yet implemented"
end TestGetDragImageOffset

-- MCPasteboardSetClipboardData
on TestSetClipboardData
   TestSkip "SetClipboardData", "not yet implemented"
end TestSetClipboardData

-- MCPasteboardSetDragData
on TestSetDragData
   TestSkip "SetDragData", "not yet implemented"
end TestSetDragData

-- MCPasteboardSetAcceptDrop
on TestSetAcceptDrop
   TestSkip "SetAcceptDrop", "not yet implemented"
end TestSetAcceptDrop

-- MCPasteboardSetDragAction
on TestSetDragAction
   TestSkip "SetDragAction", "not yet implemented"
end TestSetDragAction

-- MCPasteboardSetAllowableDragActions
on TestSetAllowableDragActions
   TestSkip "SetAllowableDragActions", "not yet implemented"
end TestSetAllowableDragActions

-- MCPasteboardSetDragImage
on TestSetDragImage
   TestSkip "SetDragImage", "not yet implemented"
end TestSetDragImage
