script "CoreInterfaceExport"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceExecExportSnapshotOfScreen
on TestExportSnapshotOfScreen
   TestSkip "ExportSnapshotOfScreen", "not yet implemented"
end TestExportSnapshotOfScreen

-- MCInterfaceExecExportSnapshotOfScreenToFile
on TestExportSnapshotOfScreenToFile
   TestSkip "ExportSnapshotOfScreenToFile", "not yet implemented"
end TestExportSnapshotOfScreenToFile

-- MCInterfaceExecExportSnapshotOfStack
on TestExportSnapshotOfStack
   TestSkip "ExportSnapshotOfStack", "not yet implemented"
end TestExportSnapshotOfStack

-- MCInterfaceExecExportSnapshotOfStackToFile
on TestExportSnapshotOfStackToFile
   TestSkip "ExportSnapshotOfStackToFile", "not yet implemented"
end TestExportSnapshotOfStackToFile

-- MCInterfaceExecExportSnapshotOfObject
on TestExportSnapshotOfObject
   TestSkip "ExportSnapshotOfObject", "not yet implemented"
end TestExportSnapshotOfObject

-- MCInterfaceExecExportSnapshotOfObjectToFile
on TestExportSnapshotOfObjectToFile
   TestSkip "ExportSnapshotOfObjectToFile", "not yet implemented"
end TestExportSnapshotOfObjectToFile

-- MCInterfaceExecExportImage
on TestExportImage
   TestSkip "ExportImage", "not yet implemented"
end TestExportImage

-- MCInterfaceExecExportImageToFile
on TestExportImageToFile
   TestSkip "ExportImageToFile", "not yet implemented"
end TestExportImageToFile
