script "CoreInterfaceGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceGetDialogData
on TestGetDialogData
   TestSkip "GetDialogData", "not yet implemented"
end TestGetDialogData

-- MCInterfaceGetLookAndFeel
on TestGetLookAndFeel
   TestSkip "GetLookAndFeel", "not yet implemented"
end TestGetLookAndFeel

-- MCInterfaceGetScreenMouseLoc
on TestGetScreenMouseLoc
   TestSkip "GetScreenMouseLoc", "not yet implemented"
end TestGetScreenMouseLoc

-- MCInterfaceGetBackdrop
on TestGetBackdrop
   TestSkip "GetBackdrop", "not yet implemented"
end TestGetBackdrop

-- MCInterfaceGetBufferImages
on TestGetBufferImages
   TestSkip "GetBufferImages", "not yet implemented"
end TestGetBufferImages

-- MCInterfaceGetSystemFileSelector
on TestGetSystemFileSelector
   TestSkip "GetSystemFileSelector", "not yet implemented"
end TestGetSystemFileSelector

-- MCInterfaceGetSystemColorSelector
on TestGetSystemColorSelector
   TestSkip "GetSystemColorSelector", "not yet implemented"
end TestGetSystemColorSelector

-- MCInterfaceGetSystemPrintSelector
on TestGetSystemPrintSelector
   TestSkip "GetSystemPrintSelector", "not yet implemented"
end TestGetSystemPrintSelector

-- MCInterfaceGetAllowInlineInput
on TestGetAllowInlineInput
   TestSkip "GetAllowInlineInput", "not yet implemented"
end TestGetAllowInlineInput

-- MCInterfaceGetDragDelta
on TestGetDragDelta
   TestSkip "GetDragDelta", "not yet implemented"
end TestGetDragDelta

-- MCInterfaceGetStackFileType
on TestGetStackFileType
   TestSkip "GetStackFileType", "not yet implemented"
end TestGetStackFileType

-- MCInterfaceGetStackFileVersion
on TestGetStackFileVersion
   TestSkip "GetStackFileVersion", "not yet implemented"
end TestGetStackFileVersion

-- MCInterfaceGetShowInvisibles
on TestGetShowInvisibles
   TestSkip "GetShowInvisibles", "not yet implemented"
end TestGetShowInvisibles

-- MCInterfaceGetCursor
on TestGetCursor
   TestSkip "GetCursor", "not yet implemented"
end TestGetCursor

-- MCInterfaceGetDefaultCursor
on TestGetDefaultCursor
   TestSkip "GetDefaultCursor", "not yet implemented"
end TestGetDefaultCursor

-- MCInterfaceGetDefaultStack
on TestGetDefaultStack
   TestSkip "GetDefaultStack", "not yet implemented"
end TestGetDefaultStack

-- MCInterfaceGetDefaultMenubar
on TestGetDefaultMenubar
   TestSkip "GetDefaultMenubar", "not yet implemented"
end TestGetDefaultMenubar

-- MCInterfaceGetDragSpeed
on TestGetDragSpeed
   TestSkip "GetDragSpeed", "not yet implemented"
end TestGetDragSpeed

-- MCInterfaceGetMoveSpeed
on TestGetMoveSpeed
   TestSkip "GetMoveSpeed", "not yet implemented"
end TestGetMoveSpeed

-- MCInterfaceGetLockCursor
on TestGetLockCursor
   TestSkip "GetLockCursor", "not yet implemented"
end TestGetLockCursor

-- MCInterfaceGetLockErrors
on TestGetLockErrors
   TestSkip "GetLockErrors", "not yet implemented"
end TestGetLockErrors

-- MCInterfaceGetLockMenus
on TestGetLockMenus
   TestSkip "GetLockMenus", "not yet implemented"
end TestGetLockMenus

-- MCInterfaceGetLockMessages
on TestGetLockMessages
   TestSkip "GetLockMessages", "not yet implemented"
end TestGetLockMessages

-- MCInterfaceGetLockMoves
on TestGetLockMoves
   TestSkip "GetLockMoves", "not yet implemented"
end TestGetLockMoves

-- MCInterfaceGetLockRecent
on TestGetLockRecent
   TestSkip "GetLockRecent", "not yet implemented"
end TestGetLockRecent

-- MCInterfaceGetIdleRate
on TestGetIdleRate
   TestSkip "GetIdleRate", "not yet implemented"
end TestGetIdleRate

-- MCInterfaceGetIdleTicks
on TestGetIdleTicks
   TestSkip "GetIdleTicks", "not yet implemented"
end TestGetIdleTicks

-- MCInterfaceGetBlinkRate
on TestGetBlinkRate
   TestSkip "GetBlinkRate", "not yet implemented"
end TestGetBlinkRate

-- MCInterfaceGetRepeatRate
on TestGetRepeatRate
   TestSkip "GetRepeatRate", "not yet implemented"
end TestGetRepeatRate

-- MCInterfaceGetRepeatDelay
on TestGetRepeatDelay
   TestSkip "GetRepeatDelay", "not yet implemented"
end TestGetRepeatDelay

-- MCInterfaceGetTypeRate
on TestGetTypeRate
   TestSkip "GetTypeRate", "not yet implemented"
end TestGetTypeRate

-- MCInterfaceGetSyncRate
on TestGetSyncRate
   TestSkip "GetSyncRate", "not yet implemented"
end TestGetSyncRate

-- MCInterfaceGetEffectRate
on TestGetEffectRate
   TestSkip "GetEffectRate", "not yet implemented"
end TestGetEffectRate

-- MCInterfaceGetDoubleDelta
on TestGetDoubleDelta
   TestSkip "GetDoubleDelta", "not yet implemented"
end TestGetDoubleDelta

-- MCInterfaceGetDoubleTime
on TestGetDoubleTime
   TestSkip "GetDoubleTime", "not yet implemented"
end TestGetDoubleTime

-- MCInterfaceGetTooltipDelay
on TestGetTooltipDelay
   TestSkip "GetTooltipDelay", "not yet implemented"
end TestGetTooltipDelay

-- MCInterfaceGetNavigationArrows
on TestGetNavigationArrows
   TestSkip "GetNavigationArrows", "not yet implemented"
end TestGetNavigationArrows

-- MCInterfaceGetExtendKey
on TestGetExtendKey
   TestSkip "GetExtendKey", "not yet implemented"
end TestGetExtendKey

-- MCInterfaceGetPointerFocus
on TestGetPointerFocus
   TestSkip "GetPointerFocus", "not yet implemented"
end TestGetPointerFocus

-- MCInterfaceGetEmacsKeyBindings
on TestGetEmacsKeyBindings
   TestSkip "GetEmacsKeyBindings", "not yet implemented"
end TestGetEmacsKeyBindings

-- MCInterfaceGetRaiseMenus
on TestGetRaiseMenus
   TestSkip "GetRaiseMenus", "not yet implemented"
end TestGetRaiseMenus

-- MCInterfaceGetActivatePalettes
on TestGetActivatePalettes
   TestSkip "GetActivatePalettes", "not yet implemented"
end TestGetActivatePalettes

-- MCInterfaceGetHidePalettes
on TestGetHidePalettes
   TestSkip "GetHidePalettes", "not yet implemented"
end TestGetHidePalettes

-- MCInterfaceGetRaisePalettes
on TestGetRaisePalettes
   TestSkip "GetRaisePalettes", "not yet implemented"
end TestGetRaisePalettes

-- MCInterfaceGetRaiseWindows
on TestGetRaiseWindows
   TestSkip "GetRaiseWindows", "not yet implemented"
end TestGetRaiseWindows

-- MCInterfaceGetHideBackdrop
on TestGetHideBackdrop
   TestSkip "GetHideBackdrop", "not yet implemented"
end TestGetHideBackdrop

-- MCInterfaceGetDontUseNavigationServices
on TestGetDontUseNavigationServices
   TestSkip "GetDontUseNavigationServices", "not yet implemented"
end TestGetDontUseNavigationServices

-- MCInterfaceGetProportionalThumbs
on TestGetProportionalThumbs
   TestSkip "GetProportionalThumbs", "not yet implemented"
end TestGetProportionalThumbs

-- MCInterfaceGetSharedMemory
on TestGetSharedMemory
   TestSkip "GetSharedMemory", "not yet implemented"
end TestGetSharedMemory

-- MCInterfaceGetScreenGamma
on TestGetScreenGamma
   TestSkip "GetScreenGamma", "not yet implemented"
end TestGetScreenGamma

-- MCInterfaceGetRelayerGroupedControls
on TestGetRelayerGroupedControls
   TestSkip "GetRelayerGroupedControls", "not yet implemented"
end TestGetRelayerGroupedControls

-- MCInterfaceGetSelectionMode
on TestGetSelectionMode
   TestSkip "GetSelectionMode", "not yet implemented"
end TestGetSelectionMode

-- MCInterfaceGetSelectionHandleColor
on TestGetSelectionHandleColor
   TestSkip "GetSelectionHandleColor", "not yet implemented"
end TestGetSelectionHandleColor

-- MCInterfaceGetWindowBoundingRect
on TestGetWindowBoundingRect
   TestSkip "GetWindowBoundingRect", "not yet implemented"
end TestGetWindowBoundingRect

-- MCInterfaceGetJpegQuality
on TestGetJpegQuality
   TestSkip "GetJpegQuality", "not yet implemented"
end TestGetJpegQuality

-- MCInterfaceGetBrush
on TestGetBrush
   TestSkip "GetBrush", "not yet implemented"
end TestGetBrush

-- MCInterfaceGetEraser
on TestGetEraser
   TestSkip "GetEraser", "not yet implemented"
end TestGetEraser

-- MCInterfaceGetSpray
on TestGetSpray
   TestSkip "GetSpray", "not yet implemented"
end TestGetSpray

-- MCInterfaceGetCentered
on TestGetCentered
   TestSkip "GetCentered", "not yet implemented"
end TestGetCentered

-- MCInterfaceGetGrid
on TestGetGrid
   TestSkip "GetGrid", "not yet implemented"
end TestGetGrid

-- MCInterfaceGetGridSize
on TestGetGridSize
   TestSkip "GetGridSize", "not yet implemented"
end TestGetGridSize

-- MCInterfaceSetSlices
on TestSetSlices
   TestSkip "SetSlices", "not yet implemented"
end TestSetSlices

-- MCInterfaceGetBeepLoudness
on TestGetBeepLoudness
   TestSkip "GetBeepLoudness", "not yet implemented"
end TestGetBeepLoudness

-- MCInterfaceGetBeepPitch
on TestGetBeepPitch
   TestSkip "GetBeepPitch", "not yet implemented"
end TestGetBeepPitch

-- MCInterfaceGetBeepDuration
on TestGetBeepDuration
   TestSkip "GetBeepDuration", "not yet implemented"
end TestGetBeepDuration

-- MCInterfaceGetBeepSound
on TestGetBeepSound
   TestSkip "GetBeepSound", "not yet implemented"
end TestGetBeepSound

-- MCInterfaceGetTool
on TestGetTool
   TestSkip "GetTool", "not yet implemented"
end TestGetTool

-- MCInterfaceGetIconMenu
on TestGetIconMenu
   TestSkip "GetIconMenu", "not yet implemented"
end TestGetIconMenu

-- MCInterfaceGetStatusIcon
on TestGetStatusIcon
   TestSkip "GetStatusIcon", "not yet implemented"
end TestGetStatusIcon

-- MCInterfaceGetStatusIconToolTip
on TestGetStatusIconToolTip
   TestSkip "GetStatusIconToolTip", "not yet implemented"
end TestGetStatusIconToolTip

-- MCInterfaceGetStatusIconMenu
on TestGetStatusIconMenu
   TestSkip "GetStatusIconMenu", "not yet implemented"
end TestGetStatusIconMenu

-- MCInterfaceGetProcessType
on TestGetProcessType
   TestSkip "GetProcessType", "not yet implemented"
end TestGetProcessType

-- MCInterfaceGetBrushPattern
on TestGetBrushPattern
   TestSkip "GetBrushPattern", "not yet implemented"
end TestGetBrushPattern

-- MCInterfaceGetPenPattern
on TestGetPenPattern
   TestSkip "GetPenPattern", "not yet implemented"
end TestGetPenPattern

-- MCInterfaceGetBrushColor
on TestGetBrushColor
   TestSkip "GetBrushColor", "not yet implemented"
end TestGetBrushColor

-- MCInterfaceGetPenColor
on TestGetPenColor
   TestSkip "GetPenColor", "not yet implemented"
end TestGetPenColor

-- MCInterfaceGetEditBackground
on TestGetEditBackground
   TestSkip "GetEditBackground", "not yet implemented"
end TestGetEditBackground

-- MCInterfaceGetRoundEnds
on TestGetRoundEnds
   TestSkip "GetRoundEnds", "not yet implemented"
end TestGetRoundEnds

-- MCInterfaceGetDashes
on TestGetDashes
   TestSkip "GetDashes", "not yet implemented"
end TestGetDashes

-- MCInterfaceGetFilled
on TestGetFilled
   TestSkip "GetFilled", "not yet implemented"
end TestGetFilled

-- MCInterfaceGetPolySides
on TestGetPolySides
   TestSkip "GetPolySides", "not yet implemented"
end TestGetPolySides

-- MCInterfaceGetLineSize
on TestGetLineSize
   TestSkip "GetLineSize", "not yet implemented"
end TestGetLineSize

-- MCInterfaceGetRoundRadius
on TestGetRoundRadius
   TestSkip "GetRoundRadius", "not yet implemented"
end TestGetRoundRadius

-- MCInterfaceGetStartAngle
on TestGetStartAngle
   TestSkip "GetStartAngle", "not yet implemented"
end TestGetStartAngle

-- MCInterfaceGetArcAngle
on TestGetArcAngle
   TestSkip "GetArcAngle", "not yet implemented"
end TestGetArcAngle

-- MCInterfaceGetLockScreen
on TestGetLockScreen
   TestSkip "GetLockScreen", "not yet implemented"
end TestGetLockScreen

-- MCInterfaceGetAccentColor
on TestGetAccentColor
   TestSkip "GetAccentColor", "not yet implemented"
end TestGetAccentColor

-- MCInterfaceGetHiliteColor
on TestGetHiliteColor
   TestSkip "GetHiliteColor", "not yet implemented"
end TestGetHiliteColor

-- MCInterfaceGetPaintCompression
on TestGetPaintCompression
   TestSkip "GetPaintCompression", "not yet implemented"
end TestGetPaintCompression

-- MCInterfaceGetLinkColor
on TestGetLinkColor
   TestSkip "GetLinkColor", "not yet implemented"
end TestGetLinkColor

-- MCInterfaceGetLinkHiliteColor
on TestGetLinkHiliteColor
   TestSkip "GetLinkHiliteColor", "not yet implemented"
end TestGetLinkHiliteColor

-- MCInterfaceGetLinkVisitedColor
on TestGetLinkVisitedColor
   TestSkip "GetLinkVisitedColor", "not yet implemented"
end TestGetLinkVisitedColor

-- MCInterfaceGetUnderlineLinks
on TestGetUnderlineLinks
   TestSkip "GetUnderlineLinks", "not yet implemented"
end TestGetUnderlineLinks

-- MCInterfaceGetSelectGroupedControls
on TestGetSelectGroupedControls
   TestSkip "GetSelectGroupedControls", "not yet implemented"
end TestGetSelectGroupedControls

-- MCInterfaceGetIcon
on TestGetIcon
   TestSkip "GetIcon", "not yet implemented"
end TestGetIcon

-- MCInterfaceGetScreenRect
on TestGetScreenRect
   TestSkip "GetScreenRect", "not yet implemented"
end TestGetScreenRect

-- MCInterfaceGetScreenRects
on TestGetScreenRects
   TestSkip "GetScreenRects", "not yet implemented"
end TestGetScreenRects

-- MCInterfaceSetDialogData
on TestSetDialogData
   TestSkip "SetDialogData", "not yet implemented"
end TestSetDialogData

-- MCInterfaceSetLookAndFeel
on TestSetLookAndFeel
   TestSkip "SetLookAndFeel", "not yet implemented"
end TestSetLookAndFeel

-- MCInterfaceSetScreenMouseLoc
on TestSetScreenMouseLoc
   TestSkip "SetScreenMouseLoc", "not yet implemented"
end TestSetScreenMouseLoc

-- MCInterfaceSetBackdrop
on TestSetBackdrop
   TestSkip "SetBackdrop", "not yet implemented"
end TestSetBackdrop

-- MCInterfaceSetBufferImages
on TestSetBufferImages
   TestSkip "SetBufferImages", "not yet implemented"
end TestSetBufferImages

-- MCInterfaceSetSystemFileSelector
on TestSetSystemFileSelector
   TestSkip "SetSystemFileSelector", "not yet implemented"
end TestSetSystemFileSelector

-- MCInterfaceSetSystemColorSelector
on TestSetSystemColorSelector
   TestSkip "SetSystemColorSelector", "not yet implemented"
end TestSetSystemColorSelector

-- MCInterfaceSetSystemPrintSelector
on TestSetSystemPrintSelector
   TestSkip "SetSystemPrintSelector", "not yet implemented"
end TestSetSystemPrintSelector

-- MCInterfaceSetAllowInlineInput
on TestSetAllowInlineInput
   TestSkip "SetAllowInlineInput", "not yet implemented"
end TestSetAllowInlineInput

-- MCInterfaceSetDragDelta
on TestSetDragDelta
   TestSkip "SetDragDelta", "not yet implemented"
end TestSetDragDelta

-- MCInterfaceSetStackFileType
on TestSetStackFileType
   TestSkip "SetStackFileType", "not yet implemented"
end TestSetStackFileType

-- MCInterfaceSetStackFileVersion
on TestSetStackFileVersion
   TestSkip "SetStackFileVersion", "not yet implemented"
end TestSetStackFileVersion

-- MCInterfaceSetShowInvisibles
on TestSetShowInvisibles
   TestSkip "SetShowInvisibles", "not yet implemented"
end TestSetShowInvisibles

-- MCInterfaceSetCursor
on TestSetCursor
   TestSkip "SetCursor", "not yet implemented"
end TestSetCursor

-- MCInterfaceSetDefaultCursor
on TestSetDefaultCursor
   TestSkip "SetDefaultCursor", "not yet implemented"
end TestSetDefaultCursor

-- MCInterfaceSetDefaultStack
on TestSetDefaultStack
   TestSkip "SetDefaultStack", "not yet implemented"
end TestSetDefaultStack

-- MCInterfaceSetDefaultMenubar
on TestSetDefaultMenubar
   TestSkip "SetDefaultMenubar", "not yet implemented"
end TestSetDefaultMenubar

-- MCInterfaceSetDragSpeed
on TestSetDragSpeed
   TestSkip "SetDragSpeed", "not yet implemented"
end TestSetDragSpeed

-- MCInterfaceSetMoveSpeed
on TestSetMoveSpeed
   TestSkip "SetMoveSpeed", "not yet implemented"
end TestSetMoveSpeed

-- MCInterfaceSetLockCursor
on TestSetLockCursor
   TestSkip "SetLockCursor", "not yet implemented"
end TestSetLockCursor

-- MCInterfaceSetLockErrors
on TestSetLockErrors
   TestSkip "SetLockErrors", "not yet implemented"
end TestSetLockErrors

-- MCInterfaceSetLockMenus
on TestSetLockMenus
   TestSkip "SetLockMenus", "not yet implemented"
end TestSetLockMenus

-- MCInterfaceSetLockMessages
on TestSetLockMessages
   TestSkip "SetLockMessages", "not yet implemented"
end TestSetLockMessages

-- MCInterfaceSetLockMoves
on TestSetLockMoves
   TestSkip "SetLockMoves", "not yet implemented"
end TestSetLockMoves

-- MCInterfaceSetLockRecent
on TestSetLockRecent
   TestSkip "SetLockRecent", "not yet implemented"
end TestSetLockRecent

-- MCInterfaceSetIdleRate
on TestSetIdleRate
   TestSkip "SetIdleRate", "not yet implemented"
end TestSetIdleRate

-- MCInterfaceSetIdleTicks
on TestSetIdleTicks
   TestSkip "SetIdleTicks", "not yet implemented"
end TestSetIdleTicks

-- MCInterfaceSetBlinkRate
on TestSetBlinkRate
   TestSkip "SetBlinkRate", "not yet implemented"
end TestSetBlinkRate

-- MCInterfaceSetRepeatRate
on TestSetRepeatRate
   TestSkip "SetRepeatRate", "not yet implemented"
end TestSetRepeatRate

-- MCInterfaceSetRepeatDelay
on TestSetRepeatDelay
   TestSkip "SetRepeatDelay", "not yet implemented"
end TestSetRepeatDelay

-- MCInterfaceSetTypeRate
on TestSetTypeRate
   TestSkip "SetTypeRate", "not yet implemented"
end TestSetTypeRate

-- MCInterfaceSetSyncRate
on TestSetSyncRate
   TestSkip "SetSyncRate", "not yet implemented"
end TestSetSyncRate

-- MCInterfaceSetEffectRate
on TestSetEffectRate
   TestSkip "SetEffectRate", "not yet implemented"
end TestSetEffectRate

-- MCInterfaceSetDoubleDelta
on TestSetDoubleDelta
   TestSkip "SetDoubleDelta", "not yet implemented"
end TestSetDoubleDelta

-- MCInterfaceSetDoubleTime
on TestSetDoubleTime
   TestSkip "SetDoubleTime", "not yet implemented"
end TestSetDoubleTime

-- MCInterfaceSetTooltipDelay
on TestSetTooltipDelay
   TestSkip "SetTooltipDelay", "not yet implemented"
end TestSetTooltipDelay

-- MCInterfaceSetNavigationArrows
on TestSetNavigationArrows
   TestSkip "SetNavigationArrows", "not yet implemented"
end TestSetNavigationArrows

-- MCInterfaceSetExtendKey
on TestSetExtendKey
   TestSkip "SetExtendKey", "not yet implemented"
end TestSetExtendKey

-- MCInterfaceSetPointerFocus
on TestSetPointerFocus
   TestSkip "SetPointerFocus", "not yet implemented"
end TestSetPointerFocus

-- MCInterfaceSetEmacsKeyBindings
on TestSetEmacsKeyBindings
   TestSkip "SetEmacsKeyBindings", "not yet implemented"
end TestSetEmacsKeyBindings

-- MCInterfaceSetRaiseMenus
on TestSetRaiseMenus
   TestSkip "SetRaiseMenus", "not yet implemented"
end TestSetRaiseMenus

-- MCInterfaceSetActivatePalettes
on TestSetActivatePalettes
   TestSkip "SetActivatePalettes", "not yet implemented"
end TestSetActivatePalettes

-- MCInterfaceSetHidePalettes
on TestSetHidePalettes
   TestSkip "SetHidePalettes", "not yet implemented"
end TestSetHidePalettes

-- MCInterfaceSetRaisePalettes
on TestSetRaisePalettes
   TestSkip "SetRaisePalettes", "not yet implemented"
end TestSetRaisePalettes

-- MCInterfaceSetRaiseWindows
on TestSetRaiseWindows
   TestSkip "SetRaiseWindows", "not yet implemented"
end TestSetRaiseWindows

-- MCInterfaceSetHideBackdrop
on TestSetHideBackdrop
   TestSkip "SetHideBackdrop", "not yet implemented"
end TestSetHideBackdrop

-- MCInterfaceSetDontUseNavigationServices
on TestSetDontUseNavigationServices
   TestSkip "SetDontUseNavigationServices", "not yet implemented"
end TestSetDontUseNavigationServices

-- MCInterfaceSetProportionalThumbs
on TestSetProportionalThumbs
   TestSkip "SetProportionalThumbs", "not yet implemented"
end TestSetProportionalThumbs

-- MCInterfaceSetSharedMemory
on TestSetSharedMemory
   TestSkip "SetSharedMemory", "not yet implemented"
end TestSetSharedMemory

-- MCInterfaceSetRelayerGroupedControls
on TestSetRelayerGroupedControls
   TestSkip "SetRelayerGroupedControls", "not yet implemented"
end TestSetRelayerGroupedControls

-- MCInterfaceSetSelectionMode
on TestSetSelectionMode
   TestSkip "SetSelectionMode", "not yet implemented"
end TestSetSelectionMode

-- MCInterfaceSetSelectionHandleColor
on TestSetSelectionHandleColor
   TestSkip "SetSelectionHandleColor", "not yet implemented"
end TestSetSelectionHandleColor

-- MCInterfaceSetWindowBoundingRect
on TestSetWindowBoundingRect
   TestSkip "SetWindowBoundingRect", "not yet implemented"
end TestSetWindowBoundingRect

-- MCInterfaceSetJpegQuality
on TestSetJpegQuality
   TestSkip "SetJpegQuality", "not yet implemented"
end TestSetJpegQuality

-- MCInterfaceSetBrush
on TestSetBrush
   TestSkip "SetBrush", "not yet implemented"
end TestSetBrush

-- MCInterfaceSetSpray
on TestSetSpray
   TestSkip "SetSpray", "not yet implemented"
end TestSetSpray

-- MCInterfaceSetCentered
on TestSetCentered
   TestSkip "SetCentered", "not yet implemented"
end TestSetCentered

-- MCInterfaceSetGrid
on TestSetGrid
   TestSkip "SetGrid", "not yet implemented"
end TestSetGrid

-- MCInterfaceSetGridSize
on TestSetGridSize
   TestSkip "SetGridSize", "not yet implemented"
end TestSetGridSize

-- MCInterfaceGetSlices
on TestGetSlices
   TestSkip "GetSlices", "not yet implemented"
end TestGetSlices

-- MCInterfaceSetBeepLoudness
on TestSetBeepLoudness
   TestSkip "SetBeepLoudness", "not yet implemented"
end TestSetBeepLoudness

-- MCInterfaceSetBeepPitch
on TestSetBeepPitch
   TestSkip "SetBeepPitch", "not yet implemented"
end TestSetBeepPitch

-- MCInterfaceSetBeepDuration
on TestSetBeepDuration
   TestSkip "SetBeepDuration", "not yet implemented"
end TestSetBeepDuration

-- MCInterfaceSetBeepSound
on TestSetBeepSound
   TestSkip "SetBeepSound", "not yet implemented"
end TestSetBeepSound

-- MCInterfaceSetTool
on TestSetTool
   TestSkip "SetTool", "not yet implemented"
end TestSetTool

-- MCInterfaceSetIconMenu
on TestSetIconMenu
   TestSkip "SetIconMenu", "not yet implemented"
end TestSetIconMenu

-- MCInterfaceSetStatusIcon
on TestSetStatusIcon
   TestSkip "SetStatusIcon", "not yet implemented"
end TestSetStatusIcon

-- MCInterfaceSetStatusIconToolTip
on TestSetStatusIconToolTip
   TestSkip "SetStatusIconToolTip", "not yet implemented"
end TestSetStatusIconToolTip

-- MCInterfaceSetStatusIconMenu
on TestSetStatusIconMenu
   TestSkip "SetStatusIconMenu", "not yet implemented"
end TestSetStatusIconMenu

-- MCInterfaceSetProcessType
on TestSetProcessType
   TestSkip "SetProcessType", "not yet implemented"
end TestSetProcessType

-- MCInterfaceSetBrushPattern
on TestSetBrushPattern
   TestSkip "SetBrushPattern", "not yet implemented"
end TestSetBrushPattern

-- MCInterfaceSetPenPattern
on TestSetPenPattern
   TestSkip "SetPenPattern", "not yet implemented"
end TestSetPenPattern

-- MCInterfaceSetBrushColor
on TestSetBrushColor
   TestSkip "SetBrushColor", "not yet implemented"
end TestSetBrushColor

-- MCInterfaceSetPenColor
on TestSetPenColor
   TestSkip "SetPenColor", "not yet implemented"
end TestSetPenColor

-- MCInterfaceSetEditBackground
on TestSetEditBackground
   TestSkip "SetEditBackground", "not yet implemented"
end TestSetEditBackground

-- MCInterfaceSetRoundEnds
on TestSetRoundEnds
   TestSkip "SetRoundEnds", "not yet implemented"
end TestSetRoundEnds

-- MCInterfaceSetDashes
on TestSetDashes
   TestSkip "SetDashes", "not yet implemented"
end TestSetDashes

-- MCInterfaceSetFilled
on TestSetFilled
   TestSkip "SetFilled", "not yet implemented"
end TestSetFilled

-- MCInterfaceSetPolySides
on TestSetPolySides
   TestSkip "SetPolySides", "not yet implemented"
end TestSetPolySides

-- MCInterfaceSetLineSize
on TestSetLineSize
   TestSkip "SetLineSize", "not yet implemented"
end TestSetLineSize

-- MCInterfaceSetRoundRadius
on TestSetRoundRadius
   TestSkip "SetRoundRadius", "not yet implemented"
end TestSetRoundRadius

-- MCInterfaceSetStartAngle
on TestSetStartAngle
   TestSkip "SetStartAngle", "not yet implemented"
end TestSetStartAngle

-- MCInterfaceSetArcAngle
on TestSetArcAngle
   TestSkip "SetArcAngle", "not yet implemented"
end TestSetArcAngle

-- MCInterfaceSetLockScreen
on TestSetLockScreen
   TestSkip "SetLockScreen", "not yet implemented"
end TestSetLockScreen

-- MCInterfaceSetAccentColor
on TestSetAccentColor
   TestSkip "SetAccentColor", "not yet implemented"
end TestSetAccentColor

-- MCInterfaceSetHiliteColor
on TestSetHiliteColor
   TestSkip "SetHiliteColor", "not yet implemented"
end TestSetHiliteColor

-- MCInterfaceSetPaintCompression
on TestSetPaintCompression
   TestSkip "SetPaintCompression", "not yet implemented"
end TestSetPaintCompression

-- MCInterfaceSetLinkColor
on TestSetLinkColor
   TestSkip "SetLinkColor", "not yet implemented"
end TestSetLinkColor

-- MCInterfaceSetLinkHiliteColor
on TestSetLinkHiliteColor
   TestSkip "SetLinkHiliteColor", "not yet implemented"
end TestSetLinkHiliteColor

-- MCInterfaceSetLinkVisitedColor
on TestSetLinkVisitedColor
   TestSkip "SetLinkVisitedColor", "not yet implemented"
end TestSetLinkVisitedColor

-- MCInterfaceSetUnderlineLinks
on TestSetUnderlineLinks
   TestSkip "SetUnderlineLinks", "not yet implemented"
end TestSetUnderlineLinks

-- MCInterfaceSetSelectGroupedControls
on TestSetSelectGroupedControls
   TestSkip "SetSelectGroupedControls", "not yet implemented"
end TestSetSelectGroupedControls

-- MCInterfaceSetIcon
on TestSetIcon
   TestSkip "SetIcon", "not yet implemented"
end TestSetIcon
