script "CoreInterfaceHide"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceExecHideGroups
on TestHideGroups
   TestSkip "HideGroups", "not yet implemented"
end TestHideGroups

-- MCInterfaceExecHideObject
on TestHideObject
   TestSkip "HideObject", "not yet implemented"
end TestHideObject

-- MCInterfaceExecHideObjectWithEffect
on TestHideObjectWithEffect
   TestSkip "HideObjectWithEffect", "not yet implemented"
end TestHideObjectWithEffect

-- MCInterfaceExecHideMenuBar
on TestHideMenuBar
   TestSkip "HideMenuBar", "not yet implemented"
end TestHideMenuBar

-- MCInterfaceExecHideTaskBar
on TestHideTaskBar
   TestSkip "HideTaskBar", "not yet implemented"
end TestHideTaskBar
