script "CoreInterfaceImport"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceExecImportSnapshotOfScreen
on TestImportSnapshotOfScreen
   TestSkip "ImportSnapshotOfScreen", "not yet implemented"
end TestImportSnapshotOfScreen

-- MCInterfaceExecImportSnapshotOfStack
on TestImportSnapshotOfStack
   TestSkip "ImportSnapshotOfStack", "not yet implemented"
end TestImportSnapshotOfStack

-- MCInterfaceExecImportSnapshotOfObject
on TestImportSnapshotOfObject
   TestSkip "ImportSnapshotOfObject", "not yet implemented"
end TestImportSnapshotOfObject

-- MCInterfaceExecImportAudioClip
on TestImportAudioClip
   TestSkip "ImportAudioClip", "not yet implemented"
end TestImportAudioClip

-- MCInterfaceExecImportVideoClip
on TestImportVideoClip
   TestSkip "ImportVideoClip", "not yet implemented"
end TestImportVideoClip

-- MCInterfaceExecImportImage
on TestImportImage
   TestSkip "ImportImage", "not yet implemented"
end TestImportImage
