script "CoreInterfaceLock"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceExecLockCursor
on TestLockCursor
   TestSkip "LockCursor", "not yet implemented"
end TestLockCursor

-- MCInterfaceExecLockMenus
on TestLockMenus
   TestSkip "LockMenus", "not yet implemented"
end TestLockMenus

-- MCInterfaceExecLockMoves
on TestLockMoves
   TestSkip "LockMoves", "not yet implemented"
end TestLockMoves

-- MCInterfaceExecLockRecent
on TestLockRecent
   TestSkip "LockRecent", "not yet implemented"
end TestLockRecent

-- MCInterfaceExecLockScreen
on TestLockScreen
   TestSkip "LockScreen", "not yet implemented"
end TestLockScreen

-- MCInterfaceExecLockScreenForEffect
on TestLockScreenForEffect
   TestSkip "LockScreenForEffect", "not yet implemented"
end TestLockScreenForEffect
