script "CoreInterfaceMouse"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceEvalMouseClick
on TestMouseClick
   TestSkip "MouseClick", "not yet implemented"
end TestMouseClick

-- MCInterfaceEvalMouseColor
on TestMouseColor
   TestSkip "MouseColor", "not yet implemented"
end TestMouseColor

-- MCInterfaceEvalMouseControl
on TestMouseControl
   TestSkip "MouseControl", "not yet implemented"
end TestMouseControl

-- MCInterfaceEvalMouseH
on TestMouseH
   TestSkip "MouseH", "not yet implemented"
end TestMouseH

-- MCInterfaceEvalMouseLoc
on TestMouseLoc
   TestSkip "MouseLoc", "not yet implemented"
end TestMouseLoc

-- MCInterfaceEvalMouseStack
on TestMouseStack
   TestSkip "MouseStack", "not yet implemented"
end TestMouseStack

-- MCInterfaceEvalMouseV
on TestMouseV
   TestSkip "MouseV", "not yet implemented"
end TestMouseV
