script "CoreInterfaceShow"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceExecShowGroups
on TestShowGroups
   TestSkip "ShowGroups", "not yet implemented"
end TestShowGroups

-- MCInterfaceExecShowAllCards
on TestShowAllCards
   TestSkip "ShowAllCards", "not yet implemented"
end TestShowAllCards

-- MCInterfaceExecShowMarkedCards
on TestShowMarkedCards
   TestSkip "ShowMarkedCards", "not yet implemented"
end TestShowMarkedCards

-- MCInterfaceExecShowCards
on TestShowCards
   TestSkip "ShowCards", "not yet implemented"
end TestShowCards

-- MCInterfaceExecShowObject
on TestShowObject
   TestSkip "ShowObject", "not yet implemented"
end TestShowObject

-- MCInterfaceExecShowObjectWithEffect
on TestShowObjectWithEffect
   TestSkip "ShowObjectWithEffect", "not yet implemented"
end TestShowObjectWithEffect

-- MCInterfaceExecShowMenuBar
on TestShowMenuBar
   TestSkip "ShowMenuBar", "not yet implemented"
end TestShowMenuBar

-- MCInterfaceExecShowTaskBar
on TestShowTaskBar
   TestSkip "ShowTaskBar", "not yet implemented"
end TestShowTaskBar
