script "CoreInterfaceUnlock"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCInterfaceExecUnlockCursor
on TestUnlockCursor
   TestSkip "UnlockCursor", "not yet implemented"
end TestUnlockCursor

-- MCInterfaceExecUnlockMenus
on TestUnlockMenus
   TestSkip "UnlockMenus", "not yet implemented"
end TestUnlockMenus

-- MCInterfaceExecUnlockMoves
on TestUnlockMoves
   TestSkip "UnlockMoves", "not yet implemented"
end TestUnlockMoves

-- MCInterfaceExecUnlockRecent
on TestUnlockRecent
   TestSkip "UnlockRecent", "not yet implemented"
end TestUnlockRecent

-- MCInterfaceExecUnlockScreen
on TestUnlockScreen
   TestSkip "UnlockScreen", "not yet implemented"
end TestUnlockScreen

-- MCInterfaceExecUnlockScreenWithEffect
on TestUnlockScreenWithEffect
   TestSkip "UnlockScreenWithEffect", "not yet implemented"
end TestUnlockScreenWithEffect
