script "CoreEngineGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCEngineSetCaseSensitive
on TestSetCaseSensitive
   TestSkip "SetCaseSensitive", "not yet implemented"
end TestSetCaseSensitive

-- MCEngineGetCenturyCutOff
on TestGetCenturyCutOff
   TestSkip "GetCenturyCutOff", "not yet implemented"
end TestGetCenturyCutOff

-- MCEngineSetCenturyCutOff
on TestSetCenturyCutOff
   TestSkip "SetCenturyCutOff", "not yet implemented"
end TestSetCenturyCutOff

-- MCEngineGetConvertOctals
on TestGetConvertOctals
   TestSkip "GetConvertOctals", "not yet implemented"
end TestGetConvertOctals

-- MCEngineSetConvertOctals
on TestSetConvertOctals
   TestSkip "SetConvertOctals", "not yet implemented"
end TestSetConvertOctals

-- MCEngineGetItemDelimiter
on TestGetItemDelimiter
   TestSkip "GetItemDelimiter", "not yet implemented"
end TestGetItemDelimiter

-- MCEngineSetItemDelimiter
on TestSetItemDelimiter
   TestSkip "SetItemDelimiter", "not yet implemented"
end TestSetItemDelimiter

-- MCEngineGetColumnDelimiter
on TestGetColumnDelimiter
   TestSkip "GetColumnDelimiter", "not yet implemented"
end TestGetColumnDelimiter

-- MCEngineSetColumnDelimiter
on TestSetColumnDelimiter
   TestSkip "SetColumnDelimiter", "not yet implemented"
end TestSetColumnDelimiter

-- MCEngineGetRowDelimiter
on TestGetRowDelimiter
   TestSkip "GetRowDelimiter", "not yet implemented"
end TestGetRowDelimiter

-- MCEngineSetRowDelimiter
on TestSetRowDelimiter
   TestSkip "SetRowDelimiter", "not yet implemented"
end TestSetRowDelimiter

-- MCEngineGetLineDelimiter
on TestGetLineDelimiter
   TestSkip "GetLineDelimiter", "not yet implemented"
end TestGetLineDelimiter

-- MCEngineSetLineDelimiter
on TestSetLineDelimiter
   TestSkip "SetLineDelimiter", "not yet implemented"
end TestSetLineDelimiter

-- MCEngineGetWholeMatches
on TestGetWholeMatches
   TestSkip "GetWholeMatches", "not yet implemented"
end TestGetWholeMatches

-- MCEngineSetWholeMatches
on TestSetWholeMatches
   TestSkip "SetWholeMatches", "not yet implemented"
end TestSetWholeMatches

-- MCEngineGetUseSystemDate
on TestGetUseSystemDate
   TestSkip "GetUseSystemDate", "not yet implemented"
end TestGetUseSystemDate

-- MCEngineSetUseSystemDate
on TestSetUseSystemDate
   TestSkip "SetUseSystemDate", "not yet implemented"
end TestSetUseSystemDate

-- MCEngineGetUseUnicode
on TestGetUseUnicode
   TestSkip "GetUseUnicode", "not yet implemented"
end TestGetUseUnicode

-- MCEngineSetUseUnicode
on TestSetUseUnicode
   TestSkip "SetUseUnicode", "not yet implemented"
end TestSetUseUnicode

-- MCEngineGetScriptParsingErrors
on TestGetScriptParsingErrors
   TestSkip "GetScriptParsingErrors", "not yet implemented"
end TestGetScriptParsingErrors

-- MCEngineGetAllowInterrupts
on TestGetAllowInterrupts
   TestSkip "GetAllowInterrupts", "not yet implemented"
end TestGetAllowInterrupts

-- MCEngineGetExplicitVariables
on TestGetExplicitVariables
   TestSkip "GetExplicitVariables", "not yet implemented"
end TestGetExplicitVariables

-- MCEngineGetPreserveVariables
on TestGetPreserveVariables
   TestSkip "GetPreserveVariables", "not yet implemented"
end TestGetPreserveVariables

-- MCEngineGetSecureMode
on TestGetSecureMode
   TestSkip "GetSecureMode", "not yet implemented"
end TestGetSecureMode

-- MCEngineGetSecurityCategories
on TestGetSecurityCategories
   TestSkip "GetSecurityCategories", "not yet implemented"
end TestGetSecurityCategories

-- MCEngineGetRecursionLimit
on TestGetRecursionLimit
   TestSkip "GetRecursionLimit", "not yet implemented"
end TestGetRecursionLimit

-- MCEngineGetAddress
on TestGetAddress
   TestSkip "GetAddress", "not yet implemented"
end TestGetAddress

-- MCEngineGetStacksInUse
on TestGetStacksInUse
   TestSkip "GetStacksInUse", "not yet implemented"
end TestGetStacksInUse

-- MCEngineGetStackLimit
on TestGetStackLimit
   TestSkip "GetStackLimit", "not yet implemented"
end TestGetStackLimit

-- MCEngineGetNumberFormat
on TestGetNumberFormat
   TestSkip "GetNumberFormat", "not yet implemented"
end TestGetNumberFormat

-- MCEngineSetAllowInterrupts
on TestSetAllowInterrupts
   TestSkip "SetAllowInterrupts", "not yet implemented"
end TestSetAllowInterrupts

-- MCEngineSetExplicitVariables
on TestSetExplicitVariables
   TestSkip "SetExplicitVariables", "not yet implemented"
end TestSetExplicitVariables

-- MCEngineSetPreserveVariables
on TestSetPreserveVariables
   TestSkip "SetPreserveVariables", "not yet implemented"
end TestSetPreserveVariables

-- MCEngineSetSecureMode
on TestSetSecureMode
   TestSkip "SetSecureMode", "not yet implemented"
end TestSetSecureMode

-- MCEngineGetSecurityPermissions
on TestGetSecurityPermissions
   TestSkip "GetSecurityPermissions", "not yet implemented"
end TestGetSecurityPermissions

-- MCEngineSetRecursionLimit
on TestSetRecursionLimit
   TestSkip "SetRecursionLimit", "not yet implemented"
end TestSetRecursionLimit

-- MCEngineSetStackLimit
on TestSetStackLimit
   TestSkip "SetStackLimit", "not yet implemented"
end TestSetStackLimit

-- MCEngineSetNumberFormat
on TestSetNumberFormat
   TestSkip "SetNumberFormat", "not yet implemented"
end TestSetNumberFormat
