script "CoreDateTimeGlobalprops"
/*
Copyright (C) 2016 LiveCode Ltd.

This file is part of LiveCode.

LiveCode is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License v3 as published by the Free
Software Foundation.

LiveCode is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with LiveCode.  If not see <http://www.gnu.org/licenses/>.  */

-- MCDateTimeGetTwelveTime
on TestGetTwelveTime
   TestSkip "GetTwelveTime", "not yet implemented"
end TestGetTwelveTime

-- MCDateTimeGetDate
on TestGetDate
   TestSkip "GetDate", "not yet implemented"
end TestGetDate

-- MCDateTimeGetTime
on TestGetTime
   TestSkip "GetTime", "not yet implemented"
end TestGetTime

-- MCDateTimeGetMilliseconds
on TestGetMilliseconds
   TestSkip "GetMilliseconds", "not yet implemented"
end TestGetMilliseconds

-- MCDateTimeGetLongMilliseconds
on TestGetLongMilliseconds
   TestSkip "GetLongMilliseconds", "not yet implemented"
end TestGetLongMilliseconds

-- MCDateTimeGetSeconds
on TestGetSeconds
   TestSkip "GetSeconds", "not yet implemented"
end TestGetSeconds

-- MCDateTimeGetLongSeconds
on TestGetLongSeconds
   TestSkip "GetLongSeconds", "not yet implemented"
end TestGetLongSeconds

-- MCDateTimeGetTicks
on TestGetTicks
   TestSkip "GetTicks", "not yet implemented"
end TestGetTicks

-- MCDateTimeGetLongTicks
on TestGetLongTicks
   TestSkip "GetLongTicks", "not yet implemented"
end TestGetLongTicks

-- MCDateTimeGetMonthNames
on TestGetMonthNames
   TestSkip "GetMonthNames", "not yet implemented"
end TestGetMonthNames

-- MCDateTimeGetWeekDayNames
on TestGetWeekDayNames
   TestSkip "GetWeekDayNames", "not yet implemented"
end TestGetWeekDayNames

-- MCDateTimeGetDateFormat
on TestGetDateFormat
   TestSkip "GetDateFormat", "not yet implemented"
end TestGetDateFormat

-- MCDateTimeSetTwelveTime
on TestSetTwelveTime
   TestSkip "SetTwelveTime", "not yet implemented"
end TestSetTwelveTime
